# Generated by Django 4.2.1 on 2023-05-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=255)),
                ('cadastro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_newsletter.cadastro')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_newsletter.servico')),
            ],
        ),
    ]
